# Generated by Django 3.0.7 on 2021-01-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
